[package]
name = "broadcast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get_if_addrs = "0.5.3"
serde = "1.0.197"
serde_json = "1.0.115"

[profile.release]
opt-level = "z"
debug = false
